## C1_W2_Lab02_Multiple_variable_Scrapbook

In [27]:
import numpy as np
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'


In [40]:
# f_wb = np.dot(w, x) + b
# features: size, bedrooms, floors, age


X_train = np.array([[2104, 5, 1, 45],
                    [1416, 3, 2, 40],
                    [852, 2, 1, 35]])

y_train = np.array([[460],
                    [232],
                    [178]])

print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")

w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083

print(f"w_init: {w_init.shape}, b_init: {b_init}")

X_train: (3, 4), y_train: (3, 1)
w_init: (4,), b_init: 785.1811367994083


In [41]:
def predict_single_loop(x, w, b):
    """
    single loop prediction using linear regression

    Args:
        x: example with multiple input features Shape (n,)
        w: weights of the model (vector, shape (n,))
        b: (scalar) bias of the model

    Returns:
        p: (scalar) prediction of the model
    """

    n = x.shape[0]
    p = 0
    for i in range(n):
        p += w[0, i] * x[i]
    p += b
    return p


In [33]:
def predict(X, w, b):
    """  
    Predicts output for training data, using w

    Args:
        X: nd_array, shape (m, n) Training set with m examples, n features
        w: nd_array, shape (1, n): row vector containing n weights
        b: scalar: bias

    Returns:
        p: nd_array, shape(m, 1): estimates based on w, b
    """

    p = np.dot(w, X.T) + b
    
    return p



In [42]:
print(np.dot(w_init, X_train.T) + b_init)
print(np.dot(X_train, w_init.T) + b_init)
print(predict(X_train, w_init, b_init))

[459.99999762 231.99999837 177.99999899]
[459.99999762 231.99999837 177.99999899]
[459.99999762 231.99999837 177.99999899]


In [57]:
def compute_cost(X, y, w, b):
    """
    Computes the cost of using w as the weight vector for linear regression to fit the data points in X and y

    Args:
        X: matrix of input features (shape: m x n)
        y: vector of output values (shape: m x 1)
        w: weight vector (shape: 1 x n)
        b: bias (scalar)

    Returns:
        cost: the cost of the model

    """

    m = X.shape[0]
    print(f'm  ={m}')
    f_wb = predict(X, w, b)
    print(f'f_wb={f_wb}, shape={f_wb.shape}')
    diff = f_wb - y_train.T
    print(f'diff={diff}')
    diff_2 = diff**2
    print(f'diff_2={diff_2}')

    cost = 1 / (2 * m) * np.sum((f_wb - y_train.T)**2)

    return cost


In [58]:
print(f'cost={compute_cost(X_train, y_train, w_init, b_init)}')

m  =3
f_wb=[459.99999762 231.99999837 177.99999899], shape=(3,)
diff=[[-2.38059170e-06 -1.63059190e-06 -1.01059175e-06]]
diff_2=[[5.66721682e-12 2.65882993e-12 1.02129568e-12]]
cost=1.5578904045996674e-12
