## C1_W2_Lab02_Multiple_variable_Scrapbook

In [10]:
import numpy as np
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'
import copy


In [11]:
# f_wb = np.dot(w, x) + b
# features: size, bedrooms, floors, age


X_train = np.array([[2104, 5, 1, 45],
                    [1416, 3, 2, 40],
                    [852, 2, 1, 35]])

y_train = np.array([[460],
                    [232],
                    [178]])

print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")

w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083

print(f"w_init: {w_init.shape}, b_init: {b_init}")

X_train: (3, 4), y_train: (3, 1)
w_init: (4,), b_init: 785.1811367994083


In [12]:
def predict_single_loop(x, w, b):
    """
    single loop prediction using linear regression

    Args:
        x: example with multiple input features Shape (n,)
        w: weights of the model (vector, shape (n,))
        b: (scalar) bias of the model

    Returns:
        p: (scalar) prediction of the model
    """

    n = x.shape[0]
    p = 0
    for i in range(n):
        p += w[0, i] * x[i]
    p += b
    return p


In [13]:
def predict(X, w, b):
    """  
    Predicts output for training data, using w

    Args:
        X: nd_array, shape (m, n) Training set with m examples, n features
        w: nd_array, shape (1, n): row vector containing n weights
        b: scalar: bias

    Returns:
        p: nd_array, shape(m, 1): estimates based on w, b
    """

    p = np.dot(w, X.T) + b
    
    return p



In [14]:
print(np.dot(w_init, X_train.T) + b_init)
print(np.dot(X_train, w_init.T) + b_init)
print(predict(X_train, w_init, b_init))

[459.99999762 231.99999837 177.99999899]
[459.99999762 231.99999837 177.99999899]
[459.99999762 231.99999837 177.99999899]


In [15]:
def compute_cost(X, y, w, b):
    """
    Computes the cost of using w as the weight vector for linear regression to fit the data points in X and y

    Args:
        X: matrix of input features (shape: m, n)
        y: vector of output values (shape: m, 1)
        w: weight vector (shape: 1, n)
        b: bias (scalar)

    Returns:
        cost: the cost of the model

    Calls:
        predict(X, w, b): returns p (shape: m, 1)
    """

    m = X.shape[0]
    #print(f'm  ={m}')
    f_wb = predict(X, w, b)
    #print(f'f_wb={f_wb}, shape={f_wb.shape}')
    diff = f_wb - y.T
    #print(f'diff={diff}')
    diff_2 = diff**2
    #print(f'diff_2={diff_2}')

    cost = 1 / (2 * m) * np.sum((f_wb - y.T)**2)

    return cost


In [16]:
print(f'cost={compute_cost(X_train[:,:].reshape(-1,4), y_train[:].reshape(-1,1), w_init, b_init)}')

cost=1.5578904045996674e-12


In [17]:
print(f'X_train[0,:]={X_train[0,:].reshape(1,4)}, shape={X_train[0,:].reshape(-1,4).shape}')
print(f'y_train[0]={y_train[0]}, shape={y_train[0].reshape(-1,1).shape}')

X_train[0,:]=[[2104    5    1   45]], shape=(1, 4)
y_train[0]=[460], shape=(1, 1)


In [33]:
def gradient_descent(X, y, w_init, b_init, alpha, numiter):
    """
    Function to calculate optimal w, b for inputs X containing n features

    Args:
        X: nd_array (m, n): Training sample 
        y: nd_array (m, 1): column vector containing training targets
        w_init: nd_array (1, n): row vector containing initial guesses for weights
        b_init: scalar: guess for initial bias
        alpha: scalar: learning rate
        numiter: scalar: number of iterations for gradient descent.

    Calls:
        predict(X, w, b): returns p (shape: m, 1))

    Returns:
        w: nd_array (1, n): row vector containing optimised weights
        b: scalar: optimised bias
        J_history: nd_array (1, numiter): row vector containing updates of cost as a function of iterations.
    """

    w = copy.deepcopy(w_init)
    b = b_init    
    J_history = []

    m = X.shape[0]

    for i in range(numiter):
        p = predict(X, w, b)
        err = p.T - y
        tmp_w = w - alpha * np.dot(err.T, X) / m
        tmp_b = b - alpha * np.sum(err.T) / m
        w = tmp_w
        b = tmp_b
        J_history.append(compute_cost(X, y, w, b))

    return w, b, J_history

In [34]:
w_init = np.zeros_like(w_init).reshape(1, 4)
print(f'w_init.shape = {w_init.shape}')
b_init = 0.0
alpha = 5.0e-7
num_iter = 1000

w, b, J_history = gradient_descent(X_train, y_train, w_init, b_init, alpha, num_iter)

print(f'w = {w}, b = {b}')

w_init.shape = (1, 4)


w = [[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ]], b = -0.002235407530932534


In [35]:
err = np.arange(0,6)
print (f'err={err[0,:,2]}')
X = np.arange(24).reshape(6,-1)+1
print(f'X = {X}')
print(f'err . X = {np.dot(err, X)}')
print(f'np.sum')

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [4]:
gf = (4.182+2.433+3.675)*(2.825+8.947)
tf = (4.182+2.433+3.675)* 7.9
print(f'gf area = {gf}')
print(f'tf area = {tf}')

gf area = 121.13387999999998
tf area = 81.291
